workflows:
  ios-release:
    name: iOS TestFlight
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.wakana.1.6180339887
      vars:
        GOOGLE_SERVICE_INFO_PLIST: $GOOGLE_SERVICE_INFO_PLIST
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Disable Swift Package Manager
        script: flutter config --no-enable-swift-package-manager
      - name: Build iOS
        script: shorebird release ios
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true